# Generated by Django 4.1.4 on 2022-12-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alien_main_page_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='deadline',
        ),
    ]
