# Generated by Django 4.1.4 on 2022-12-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_login', models.CharField(max_length=150)),
                ('user_password', models.CharField(max_length=150)),
                ('user_name', models.CharField(max_length=150)),
                ('user_surname', models.CharField(blank=True, max_length=150)),
                ('user_work_position', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
